"""Addresses GENERATED by gen_symbols.py -- do not edit by hand.
Source: decomp projectPiki/pikmin (GPIP01_00, GPIE01_01).
Regenerate: python gen_symbols.py <decomp>/config worlds/pikmin/P1Symbols.py
"""

# gameflow (day, time, unlocked areas)
SYM_GAMEFLOW = {
    b'GPIP01': {
        "UNLOCKED_AREAS": 0x803A2803,
        "PENDING_STAGE_UNLOCK": 0x803A2808,
        "CURRENT_STAGE_ID": 0x803A2804,
        "GAME_SECTION": 0x803A2824,
        "DAY_END_TRIGGERED": 0x803A281E,
        "TIME_OF_DAY": 0x803A2928,
        "PAUSE_ALLOWED": 0x803A296C,
        "UI_OVERLAY_ACTIVE": 0x803A2970,
        "PAUSE_ALL": 0x803A2974,
        "TUTORIAL_TEXT_ACTIVE": 0x803A2978,
        "MOVIE_PLAYER_PTR": 0x803A2814,
        "SAVE_GAME_CRC": 0x803A27D8,
        "PLAYSTATE_SAVE_STATUS": 0x803A27FC,
        "PLAYSTATE_SAVED_DAY": 0x803A27FD,
        "FILE_SLOT": 0x803A27D4,
        "ONEPLAYER_SECTION": 0x803A282C,
        "SENTINEL": 0x803A2924,
        "TIME_HOURS": 0x803A2930,
        "DAY_NUMBER": 0x803A2937,
        "SHIP_TEXT_PARTID": 0x803A2818,
        "SHIP_TEXT_TYPE": 0x803A281A,
    },
    b'GPIE01': {
        "UNLOCKED_AREAS": 0x8039D983,
        "PENDING_STAGE_UNLOCK": 0x8039D988,
        "CURRENT_STAGE_ID": 0x8039D984,
        "GAME_SECTION": 0x8039D9A4,
        "DAY_END_TRIGGERED": 0x8039D99E,
        "TIME_OF_DAY": 0x8039DAA8,
        "PAUSE_ALLOWED": 0x8039DAEC,
        "UI_OVERLAY_ACTIVE": 0x8039DAF0,
        "PAUSE_ALL": 0x8039DAF4,
        "TUTORIAL_TEXT_ACTIVE": 0x8039DAF8,
        "MOVIE_PLAYER_PTR": 0x8039D994,
        "SAVE_GAME_CRC": 0x8039D958,
        "PLAYSTATE_SAVE_STATUS": 0x8039D97C,
        "PLAYSTATE_SAVED_DAY": 0x8039D97D,
        "FILE_SLOT": 0x8039D954,
        "ONEPLAYER_SECTION": 0x8039D9AC,
        "SENTINEL": 0x8039DAA4,
        "TIME_HOURS": 0x8039DAB0,
        "DAY_NUMBER": 0x8039DAB7,
        "SHIP_TEXT_PARTID": 0x8039D998,
        "SHIP_TEXT_TYPE": 0x8039D99A,
    },
}

# formationPikis__8GameStat -- low byte per color
SYM_PIKMIN_ADDRESSES = {
    b'GPIP01': {
        "blue": 0x803D6CF3,
        "red": 0x803D6CF7,
        "yellow": 0x803D6CFB,
    },
    b'GPIE01': {
        "blue": 0x803D1E73,
        "red": 0x803D1E77,
        "yellow": 0x803D1E7B,
    },
}

# containerPikis__8GameStat -- total per color
SYM_ONION_DYN_ADDRS = {
    b'GPIP01': {
        "blue": 0x803D6D20,
        "red": 0x803D6D24,
        "yellow": 0x803D6D28,
    },
    b'GPIE01': {
        "blue": 0x803D1EA0,
        "red": 0x803D1EA4,
        "yellow": 0x803D1EA8,
    },
}

# allPikis__8GameStat -- live total ACTUALLY shown on the HUD (mTotalPikiNum)
SYM_ALLPIKIS_ADDRS = {
    b'GPIP01': {
        "blue": 0x803D6D50,
        "red": 0x803D6D54,
        "yellow": 0x803D6D58,
    },
    b'GPIE01': {
        "blue": 0x803D1ED0,
        "red": 0x803D1ED4,
        "yellow": 0x803D1ED8,
    },
}

# pikiInfMgr.mPikiCounts[color][stage] (u32)
SYM_ONION_STAGE_ADDRS = {
    b'GPIP01': {
        "blue": {"leaf": 0x803D6C70, "bud": 0x803D6C74, "flower": 0x803D6C78},
        "red": {"leaf": 0x803D6C7C, "bud": 0x803D6C80, "flower": 0x803D6C84},
        "yellow": {"leaf": 0x803D6C88, "bud": 0x803D6C8C, "flower": 0x803D6C90},
    },
    b'GPIE01': {
        "blue": {"leaf": 0x803D1DF0, "bud": 0x803D1DF4, "flower": 0x803D1DF8},
        "red": {"leaf": 0x803D1DFC, "bud": 0x803D1E00, "flower": 0x803D1E04},
        "yellow": {"leaf": 0x803D1E08, "bud": 0x803D1E0C, "flower": 0x803D1E10},
    },
}

# playerState -- global POINTER, must be dereferenced before use
SYM_PLAYER_STATE_PTR = {
    b'GPIP01': 0x803ECB4C,
    b'GPIE01': 0x803E7C8C,
}

# itemMgr -- global POINTER to ItemMgr
SYM_ITEM_MGR_PTR = {
    b'GPIP01': 0x803ECC8C,
    b'GPIE01': 0x803E7DCC,
}

# DeathLink -- deadPikis (ColCounter: 3 ints Blue/Red/Yellow, total = sum).
SYM_DEAD_PIKIS = {
    b'GPIP01': 0x803D6CD8,
    b'GPIE01': 0x803D1E58,
}

# bornPikis (ColCounter: 3 ints Blue/Red/Yellow), Pikmin sprouted today.
SYM_BORN_PIKIS = {
    b'GPIP01': 0x803D6D2C,
    b'GPIE01': 0x803D1EAC,
}

# DeathLink -- orimaDead (bool, 1 = Olimar dead). Set to 1 by NaviDeadState.
SYM_ORIMA_DEAD = {
    b'GPIP01': 0x803ECCE8,
    b'GPIE01': 0x803E7E28,
}

# naviMgr -- global POINTER to NaviMgr (used to reach Olimar).
SYM_NAVI_MGR_PTR = {
    b'GPIP01': 0x803ECD00,
    b'GPIE01': 0x803E7E40,
}

# Chain naviMgr -> Olimar (Navi) and Navi/Creature fields.
#   naviMgr -> +MONO_OBJECTLIST (Creature**) -> [0] = Navi (Olimar, single player)
#   Navi + CREATURE_HEALTH = mHealth (f32), <= 1.0 => dead
#   Navi + NAVI_STATEMACHINE = mStateMachine
NAVI_CHAIN = {
    "MONO_OBJECTLIST": 0x28,
    "CREATURE_HEALTH": 0x58,
    "NAVI_STATEMACHINE": 0x320,
    "NAVI_PRESSED_TIMER": 0x814,
    "NAVI_CURRSTATE": 0xADC,
    "CREATURE_POSITION": 0x94,
    "CREATURE_STICKLIST": 0x180,
    "NAVI_KONTROLLER": 0x2E4,
    "CONTROLLER_INPUT_PRESSED": 0x28,
    "SM_STATES": 0x4,
    "SM_STATEINDEXES": 0x14,
    # Navi.mGoalItem (_708, include/Navi.h): GoalItem (onion) that Olimar is
    # using while the onion menu is open. Tells which onion the player really
    # used (not just walked past), so onion tracking (hasContainer) is enabled
    # only for that color.
    "NAVI_GOALITEM": 0x708,
}
NAVISTATE_DEAD = 29     # enum NaviStateID (include/NaviState.h) -- dead state
NAVISTATE_PRESSED = 7   # 'pressed' state: its exec() checks health and transitions to Dead
NAVISTATE_WALK = 0      # walk state: its exec() transitions to Stuck if mStickListHead != 0
KBBTN_X = 0x4000        # X button = default disband key (keyConfig.cpp:39)

# routeMgr -- global POINTER to RouteMgr (Pikmin navigation graph).
# Used by the Teleport Trap: Olimar is teleported to a valid waypoint (so
# always onto navigable ground, never into the void).
SYM_ROUTE_MGR_PTR = {
    b'GPIP01': 0x803ECC0C,
    b'GPIE01': 0x803E7D4C,
}
# Chain routeMgr -> waypoints and WayPoint fields (include/Route.h).
ROUTE_CHAIN = {
    "ROUTEMGR_GROUPLIST": 0x20,
    "GROUP_WAYPOINTS": 0x0,
    "GROUP_NUMPOINTS": 0x4,
    "WAYPOINT_SIZE": 0xC4,
    "WP_POSITION": 0x0,
    "WP_ISOPEN": 0x38,
    "WP_FLAGS": 0x40,
}
WP_FLAG_INWATER = 0x01  # WayPointFlags::InWater (bit 0)

# enum GameSectionID (include/Section.h). Value of gameflow.mCurrGameSectionID.
SECTION_ONE_PLAYER = 4  # story/challenge mode: a game is loaded
SECTION_TITLES = 1      # title screen

# enum OnePlayerSectionID (include/Section.h). Value of mNextOnePlayerSectionID.
ONEPLAYER_NEW_PIKI_GAME = 7  # actual game day (Olimar in a stage)
ONEPLAYER_CARD_SELECT = 1    # save file selection menu
ONEPLAYER_MAP_SELECT = 6     # world map / zone selection

# tutorialWindow -- static POINTER to zen::ogScrTutorialMgr
# (created in createTutorialWindow(), src/plugPikiColin/newPikiGame.cpp).
SYM_TUTORIAL_WINDOW_PTR = {
    b'GPIP01': 0x803ECA68,
    b'GPIE01': 0x803E7BA8,
}

# Chain to the text shown on screen:
#   tutorialWindow -> ogScrTutorialMgr +MESSAGEMGR -> ogScrMessageMgr
#   -> +FORMATTED_STRINGS (mFormattedDisplayStrings[20][0x400])
# Offsets from include/zen/ogTutorial.h and include/zen/ogMessage.h.
# The structure does not depend on the version: identical on PAL/NTSC.
TUTORIAL_TEXT_CHAIN = {
    "TUTORIALMGR_MESSAGEMGR": 0x0,
    "TUTORIALMGR_STATUS": 0x4,
    "MSGMGR_PAGE_INFOS": 0x1C,
    "MSGMGR_STATE": 0x4CC,
    "MSGMGR_CURR_PAGE": 0x4D0,
    "MSGMGR_FORMATTED": 0x4F2,
    "MSGMGR_RAW": 0x554C,
    "MSGMGR_STRING_STRIDE": 0x400,
    "TEXTINFO_MSG_UNIQUE_ID": 0x4,
}

# Ranges of the EnumTutorial enum (include/zen/ogTutorial.h) covering
# the ship part texts. Each range spans the 30 parts, in UfoPartIndex
# order. Any ID outside these ranges is a tutorial or scenario text
# and must NOT be replaced.
TUT_PART_TEXT_RANGES = {
    "discovery": 32,
    "info": 62,
    "collect": 92,
    "power": 122,
}

# MessageStatus (include/zen/ogMessage.h): the REAL state of the text window,
# in ogScrMessageMgr.mState (offset MSGMGR_STATE = 0x4CC). ogScrTutorialMgr.mStatus
# is only a mirror recomputed every frame from mState, so write HERE.
# Writing STATE_Exiting closes the window on the next update (like the end of a text).
MSG_STATE_EXITING = 4

# EDemoFlags of the "container out/in" explanation (text TUT_OnyonInOut = 12,
# "the red onion followed you") triggered by Navi::demoCheck as soon as !isTutorial
# (so on the first landing with normal_first_day). It is PRE-MARKED "seen" to
# cancel the trigger upstream: closing the window afterwards soft-locks (the
# associated demo/camera stays active). No side effects (target is nullptr).
DEMOFLAG_ONYON_MENU_INFO = 16  # DEMOFLAG_OnyonMenuInfo

# EDemoFlags indices (include/Demo.h) of the onion discovery cutscenes.
DEMOFLAG_DISCOVER_ONION = {
    "red": 0,     # DEMOFLAG_DiscoverRedOnyon
    "yellow": 1,  # DEMOFLAG_DiscoverYellowOnyon
    "blue": 2,    # DEMOFLAG_DiscoverBlueOnyon
}

# EDemoFlags indices of the first-pluck cutscenes for each Pikmin color.
DEMOFLAG_PLUCK_PIKMIN = {
    "red": 4,     # DEMOFLAG_PluckRedPikmin
    "yellow": 5,  # DEMOFLAG_PluckYellowPikmin
    "blue": 6,    # DEMOFLAG_PluckBluePikmin
}

# EDemoFlags of the first pellet delivered to an onion (text TUT_Pelette = 6).
DEMOFLAG_COLLECT_FIRST_PELLET = 10  # DEMOFLAG_CollectFirstPellet

# EDemoFlags of the Main Engine discovery in The Impact Site.
DEMOFLAG_APPROACH_ENGINE = 12  # DEMOFLAG_ApproachEngine

# EDemoFlags of COLLECTING the Main Engine (first part). Marking it "seen" makes
# the collection take the "normal part" branch of PelletGoalState::init (whose
# movie(DEMOID_CollectPart) is already nop-ed by the DOL patch) instead of the
# tutorial branch that plays movie(20). -> no cutscene for the engine.
DEMOFLAG_COLLECT_ENGINE = 13  # DEMOFLAG_CollectEngine

# EDemoFlags of the "10 Pikmin push the box" cutscene (The Impact Site).
DEMOFLAG_BOX_PUSH = (14, 15)  # StartBoxPush (film) + FinishBoxPush

# EDemoFlags of the "yellow Pikmin brings back a bomb" cutscene (text
# TUT_FoundBomb = 16), set in ActCrowd (aiCrowd.cpp) via DEMOFLAG_GrabFirstBomb.
DEMOFLAG_GRAB_FIRST_BOMB = 18  # DEMOFLAG_GrabFirstBomb

# EDemoFlags of the nectar explanation text (TUT_Mitu = 22).
DEMOFLAG_FIRST_NECTAR = 26  # DEMOFLAG_FirstNectar

# EDemoFlags of the first bomb explosion text (TUT_BombInfo = 20). Sent directly
# in DemoFlags::update(), which short-circuits via isFlag(), so pre-marking the
# flag is enough to cancel the text.
DEMOFLAG_FIRST_BOMB_EXPLODE = 20  # DEMOFLAG_FirstBombExplode

# EDemoFlags of the Olimar damage text (shows ID 24 in game; the flag is
# named "ORIMA DAMAGED" in the decomp).
DEMOFLAG_OLIMAR_LOW_HEALTH = 29  # DEMOFLAG_OlimarLowHealth

# EDemoFlags of the blocked carry path text (TUT_Rute = 23;
# flag "GURU GURU" = Pikmin walking in circles).
DEMOFLAG_CARRY_PATH_BLOCKED = 28  # DEMOFLAG_CarryPathBlocked

# EDemoFlags of the "you have more than 100 Pikmin" texts (one per zone, 21..25).
DEMOFLAG_PIKMIN_LIMIT = (21, 22, 23, 24, 25)

# EDemoFlags of the info text shown at the first noon (TUT_InfoDisplay = 31),
# triggered in GameCoreSection::update guarded by !isFlag(DEMOFLAG_FirstNoon).
DEMOFLAG_FIRST_NOON = 31  # DEMOFLAG_FirstNoon
# DEMOFLAG_FirstHurryUp -- text TUT_DayEnd (19) "the clock shows that sunset
# is approaching", shown once after the first "Hurry Up!"
# (zen::DrawHurryUp, drawHurryUp.cpp).
DEMOFLAG_FIRST_HURRY_UP = 19

# Address of the 0.9999f float constant of the stumble test
# (ActCrowd::exec: `getRand(1.0f) >= 0.9999f`), in .sdata2, per version.
# "item" mode of Disable Pikmin Trip: when the item is received, the client writes
# 2.0f here. getRand(1.0f) returns [0,1[ so the condition is never true -> no
# more trips. This is DATA (not code): Dolphin's JIT rereads it on every
# execution, unlike a hot code rewrite which has no effect.
# This copy of 0.9999 is used ONLY by the trip test (the other 0.9999 tests in
# the game use other .sdata2 copies). PAL verified on the ISO; NTSC
# derived from the decomp (see below).
SYM_TRIP_RAND_CONST = {
    b"GPIP01": 0x803EE264,
    # NTSC: same constant @2356 of aiCrowd.cpp. The .sdata2 of aiCrowd has an
    # identical layout in both versions (decomp config/*/symbols.txt:
    # PAL 0x803EE230 + 0x34, NTSC 0x803E9310 + 0x34).
    b"GPIE01": 0x803E9344,
}
TRIP_DISABLED_FLOAT = 2.0  # written in place of 0.9999 to cancel the trip
TRIP_NORMAL_FLOAT = 0.9999  # original game value
TRIP_FORCED_FLOAT = 0.0     # Trip Trap: first test always true -> ~30 % per test

# ---------------------------------------------------------------------------
# OptionSet "skip_events": readable key -> EDemoFlags indices to pre-mark.
# A key present in the player's OptionSet = this cutscene / text is
# skipped (the client pre-marks the matching DemoFlags).
#   - "Onion Discovery" also triggers the onion follow/display repair
#     (see handle_qol_skip_cutscenes).
#   - "Part Collection" ADDITIONALLY implies the DOL patch of the collection movie.
#   - "Ship Upgrade" is a DOL patch only (no DemoFlag) -> not listed here.
# ---------------------------------------------------------------------------
SKIP_EVENT_DEMOFLAGS = {
    # --- Cutscenes ---
    "Onion Discovery":       tuple(DEMOFLAG_DISCOVER_ONION.values()),
    "New Pikmin":            tuple(DEMOFLAG_PLUCK_PIKMIN.values()),
    "Main Engine Discovery": (DEMOFLAG_APPROACH_ENGINE,),
    "First Pellet":          (DEMOFLAG_COLLECT_FIRST_PELLET,),
    "Part Collection":       (DEMOFLAG_COLLECT_ENGINE,),  # + DOL patch
    "Box Push":              tuple(DEMOFLAG_BOX_PUSH),
    "First Bomb":            (DEMOFLAG_GRAB_FIRST_BOMB,),
    # --- Texts ---
    "Pikmin Limit":          tuple(DEMOFLAG_PIKMIN_LIMIT),
    "Bomb Explosion":        (DEMOFLAG_FIRST_BOMB_EXPLODE,),
    "Olimar Damage":         (DEMOFLAG_OLIMAR_LOW_HEALTH,),
    "Carry Path":            (DEMOFLAG_CARRY_PATH_BLOCKED,),
    "First Noon":            (DEMOFLAG_FIRST_NOON,),
    "Onion Followed":        (DEMOFLAG_ONYON_MENU_INFO,),
    "Nectar":                (DEMOFLAG_FIRST_NECTAR,),
    "Sunset Warning":        (DEMOFLAG_FIRST_HURRY_UP,),
}
# All valid OptionSet keys (DemoFlags + "Ship Upgrade" DOL-only).
SKIP_EVENT_ALL_KEYS = tuple(SKIP_EVENT_DEMOFLAGS.keys()) + ("Ship Upgrade",)

# PlayerState.mContainerFlag (offset 0x184): byte 00 yyy xxx.
#   x (bits 0..2) = hasContainer(color): the onion is owned and follows between zones.
#       bit = 1 << colorIndex (Blue=0, Red=1, Yellow=2).
#   y (bits 3..5) = hasBootContainer(color): the onion is "started" (active).
#       bit = 1 << (colorIndex + 3).
# Skipping the discovery cutscene deprives the game of these updates, so we
# reproduce them (boot to activate, container for tracking across days/zones).
CONTAINER_COLOR_BIT = {"blue": 0x01, "red": 0x02, "yellow": 0x04}  # hasContainer (x)
CONTAINER_BOOT_ALL = 0x38  # all hasBootContainer (y) bits, bits 3/4/5

# enum UfoPartIndex (include/Pellet.h) -> part name in ALL_PARTS.
# The index read from gameflow.mShipTextPartID indexes this list directly.
UFO_PART_ORDER = [
    'Bowsprit',
    'Gluon Drive',
    'Anti-Dioxin Filter',
    'Eternal Fuel Dynamo',
    'Main Engine',
    'Whimsical Radar',
    'Interstellar Radio',
    'Guard Satellite',
    'Chronos Reactor',
    'Radiation Canopy',
    'Geiger Counter',
    'Sagittarius',
    'Libra',
    'Omega Stabilizer',
    '#1 Ionium Jet',
    '#2 Ionium Jet',
    'Shock Absorber',
    'Gravity Jumper',
    "Pilot's Seat",
    'Nova Blaster',
    'Automatic Gear',
    'Zirconium Rotor',
    'Extraordinary Bolt',
    'Repair-type Bolt',
    'Space Float',
    'Massage Machine',
    'Secret Safe',
    'Positron Generator',
    'Analog Computer',
    'UV Lamp',
]
UFO_NOPART = -1  # no part / invalid index

# gsys -- global POINTER to System (System : public StdSystem, include/system.h)
SYM_GSYS_PTR = {
    b'GPIP01': 0x803EC9CC,
    b'GPIE01': 0x803E7B0C,
}

# StdSystem.mLanguageID (include/system.h). PAL-only member:
# on NTSC-U the field does not exist (English-only game) and 0x1A0 holds
# the vtable pointer -- never read it outside GPIP01.
STDSYSTEM_LANGUAGE_OFFSET = 0x1A0

# enum LanguageID (include/system.h). WARNING: this order is NOT
# the GameCube OS one (OS_LANG_GERMAN=1 / OS_LANG_FRENCH=2); the game
# remaps through the ids[] table of GamePrefs::Initialise().
LANGUAGE_IDS = {
    0: "en",
    1: "fr",
    2: "de",
    3: "es",
    4: "it",
}

# Pointer chain to the live onions (replaces the RAM scan).
# itemMgr -> +MELTINGPOT -> +ROOTNODE +CHILD -> [ +MCREATURE ] -> GoalItem
# then follow +NEXT from node to node.
ONION_CHAIN = {
    "ITEMMGR_MELTINGPOT": 0x68,
    "MGR_ROOTNODE": 0x28,
    "NODE_NEXT": 0xC,
    "NODE_CHILD": 0x10,
    "NODE_CREATURE": 0x14,
    "CREATURE_OBJTYPE": 0x6C,
    "GOAL_COLOUR": 0x428,
    "GOAL_HELDPIKIS": 0x42C,
}
OBJTYPE_GOAL = 16  # ObjType.h
OBJTYPE_PELLET = 52  # ObjType.h -- all pellets (including ship parts)

# pelletMgr -- global POINTER to PelletMgr (MonoObjectMgr of pellets,
# including ship parts). Pellets live HERE, NOT in itemMgr.
SYM_PELLET_MGR_PTR = {
    b'GPIP01': 0x803ECBFC,
    b'GPIE01': 0x803E7D3C,
}
# MonoObjectMgr fields (include/ObjectMgr.h) + Pellet/PelletConfig
# (include/Pellet.h) to enumerate and remove a ship part Pellet.
PELLET_CHAIN = {
    "MONO_OBJECTLIST": 0x28,
    "MONO_MAXELEMENTS": 0x2C,
    "MONO_ENTRYSTATUS": 0x34,
    "PELLET_CONFIG": 0x55C,
    "PELLETCONFIG_MODELID": 0x2C,
    "PELLET_ISALIVE": 0x5B8,
}
ENTRYSTATUS_KILL = -2  # mEntryStatus[i] = -2 -> MonoObjectMgr::update kills the object

# radarInfo -- global POINTER to RadarInfo. The radar draws one icon
# per mAlivePartsList node; removing a part = unlinking its node
# (like RadarInfo::detachParts). Nodes = CoreNode (mNext _0C), mPart _14.
SYM_RADAR_INFO_PTR = {
    b'GPIP01': 0x803ECB08,
    b'GPIE01': 0x803E7C48,
}
RADAR_CHAIN = {
    "ALIVE_CHILD": 0x10,
    "NODE_NEXT": 0xC,
    "NODE_PART": 0x14,
}

# Offsets in the PlayerState struct (include/PlayerState.h)
PLAYERSTATE_OFFSETS = {
    # int mSproutedNum (_00) = "total sprouts"; TimeGraph mPerHourGraph
    # (_18C: u16 mStartTime, u16 mEndTime, PikiNum* mEntries @+4, PikiNum =
    # int[3] Blue/Red/Yellow) = end-of-day population graph.
    "mSproutedNum": 0x00,
    "mPerHourGraph": 0x18C,
    "mShipEffectPartFlag": 0x11,
    "mTotalRegisteredParts": 0x170,
    "mTotalParts": 0x174,
    "mCurrParts": 0x17C,
    "mRequiredUfoPartCount": 0x180,
    "mContainerFlag": 0x184,
    # Visual stage of the S.S. Dolphin (0=broken, 1..4=intermediate stages,
    # 5=PERFECT/repaired). Distinct from mCurrParts: the game only updates it
    # in PlayerState::registerPart(), never recomputes it automatically
    # from the part count -- so we must write it ourselves.
    "mShipUpgradeLevel": 0x10,
    # PlayerState.mDemoFlags (_54) is a DemoFlags; its mStoredFlags field (_08)
    # is a pointer to u8[32] (bitset of already seen cutscenes, indexed by
    # EDemoFlags). Offset of the POINTER in PlayerState: 0x54 + 0x08 = 0x5C.
    # Setting a bit = the matching cutscene no longer plays (the game sees
    # isFlag()==true). include/Demo.h + include/PlayerState.h.
    "mDemoFlagsStoredPtr": 0x5C,
    # bool PlayerState.mIsTutorialMode (_185, include/PlayerState.h). isTutorial()
    # returns it as is. TRUE => special day 1: crash intro (DEMOID_OlimarWakeUp),
    # frozen clock and tutorial pop-ups. Forcing it to 0 gives a regular day 1.
    "mIsTutorialMode": 0x185,
    "mStagePartsCollected": 0x187,
    # u8 PlayerState.mDisplayPikiFlag (_1AC): bit (1<<color) for each color whose
    # Pikmin counter is displayed (HUD, world map, end-of-day summary).
    # Set by setDisplayPikiCount(). Skipping the onion discovery leaves it at 0
    # for blue/yellow, which would hide owned onions in the menus.
    "mDisplayPikiFlag": 0x1AC,
    "mLivingPikiNum": 0x1A8,
    "mPartsCollectedByDay": 0x18,
}

# mapWindow -- file-level static (zen::DrawWorldMap*) of mapSelect.cpp:
# the story mode world map. Used to refresh unlocked zones and the part
# counter IN PLACE when a part arrives while the player is already on the
# map, without leaving it or restarting a day.
SYM_MAP_WINDOW_PTR = {
    b'GPIP01': 0x803ECA34,
    b'GPIE01': 0x803E7B74,
}
# "game" zone index (Impact, Forest, Navel, Spring, Final) -> "screen" index
# (mapNoGame2Scr table, .sdata). Verified: Yakushima=0, Forest=1, Practice=2,
# Cave=3, Last=4. Identical on PAL/NTSC.
MAP_GAME2SCR = (2, 1, 3, 0, 4)
# Map refresh offsets (identical on all versions).
#   DrawWorldMap (include/zen/DrawWorldMap.h)
#   WorldMapCoursePointMgr / WorldMapCoursePoint (src/plugPikiYamashita/drawWorldMap.cpp)
WORLDMAP_CHAIN = {
    "DWM_CURRENTMODE":    0x04,  # int DrawWorldMap.mCurrentMode (2 = Operation)
    "DWM_COURSEPOINTMGR": 0x38,  # WorldMapCoursePointMgr*
    "DWM_CURRPARTS":      0x40,  # int DrawWorldMap.mCurrentPartsNum (bottom-left counter)
    "CPM_MODE":           0x00,  # int WorldMapCoursePointMgr.mMode (1 = Appear)
    "CPM_POINTS":         0x08,  # WorldMapCoursePoint mCoursePoints[5]
    "CP_STRIDE":          0x3C,  # sizeof(WorldMapCoursePoint)
    "CP_APPEARSTATE":     0x04,  # int WorldMapCoursePoint.mAppearState
    "CP_APPEARTIMER":     0x08,  # f32 WorldMapCoursePoint.mAppearTimer
    "CP_ISVISIBLE":       0x0C,  # bool WorldMapCoursePoint.mIsVisible
}
DWM_MODE_OPERATION = 2  # DrawWorldMapMode::Operation (idle map)
CPM_MODE_APPEAR    = 1  # CoursePointMode::Appear (plays the reveal animation)
CP_APPEAR_START    = 1  # CourseAppearState::RocketIncoming (starts the animation)
